AllCops:
  NewCops: enable
Style/MethodDefParentheses:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/LineLength:
  Max: 100
Layout/EndOfLine:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/MethodLength:
  Max: 25
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
